# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- twitter_widget

# Miscellaneous
google_analytics: "UA-54389737-1"
favicon: /favicon.png
twitter: 
	username: kyusyukeigo
	widget_id: "479529444873220097"
google_plus:
fb_admins:
fb_app_id: